'program : 'start' (whitespace)* OPEN_BRACE statement_list CLOSE_BRACE (whitespace)* 'end'

statement_list : statement | statement SEMICOLON statement_list

statement: assignment_statement
         | variable_declaration
         | reassignment_statement
         | print_statement
         | empty

print_statement: PRINT expression

assignment_statement: TYPE variable ASSIGN expression

reassignment_statement: variable ASSIGN expression

variable_declaration: TYPE variable

empty:

expression: term ((PLUS | SUBTRACT) term)*

term: factor ((MULTIPLY | DIVIDE) factor)*

factor: PLUS factor
      | SUBTRACT factor
      | INTEGER
      | OPEN_PAREN expression CLOSE_PAREN
      | variable

variable: IDENTIFIER

whitespace : ' ' | '\n' | '\r' | '\t'

TYPE : 'float' | 'int' | 'string'
