#!/bin/sh
# TODO write a makefile. Build scripts like this are temporary hacks.
echo "Building lexer..."
gcc -c lexer.c
echo "Building token..."
gcc -c token.c
echo "Building binary_op..."
gcc -c binary_op.c
echo "Building mpl_object..."
gcc -c mpl_object.c
echo "Building lexer test..."
gcc test_lexer.c binary_op.o lexer.o token.o mpl_object.o -o test_lexer
echo "Building binary_op test..."
gcc test_binary_op.c mpl_object.o binary_op.o token.o -o test_binary_op
echo "Done building!"
