; tma-16 assembly code
; Code generated by the MPL compiler

; entry point of the program
jmp @__start__
    
; unimplemented feature: (<built-in function readln>)

; function one()
@one:
  movl  ra 1 ; return 1
  pop   ip ; exit function


; unimplemented feature: 
  pop   ip ; exit function

; entry point of the program
@__start__:

; unimplemented feature: (setq i 68)

; unimplemented feature: (setq i (+ i (one)))

; unimplemented feature: (format t "~a" (+ i "\n"))

; unimplemented feature: (format t "~a" "Nice\n")

; unimplemented feature: 
  halt ; end of program
