; tma-16 assembly code
; Code generated by the MPL compiler

; entry point of the program
jmp @__start__

; library subroutines
#include "include/print.asm"
#include "include/compare_strings.asm"
#include "include/math.asm"
#include "include/memstack.asm"

#define MEM_STACK_SPACE__ 0x1000
#define HEAP_SPACE__ 0x8000
    
; unimplemented feature: (<built-in function readln>)

; function one()
@one:
  movl  ra   1 ; return 1
  pop   ip ; exit function


; unimplemented feature: 
  pop   ip ; exit function

; entry point of the program
@__start__:
; TODO save registers
  movl  ra   48879 ; printing u16 48879
  movl  rb   @__ret1 ; return address
  push  rb ; return address goes on the stack first
  push  ra ; u16 to print
  jmp      @__print_u16__ ; call the subroutine
@__ret1: ; go here after printing
; TODO load registers

; unimplemented feature: 
  halt ; end of program
;
; in-memory stack (not to be confused with the "hardware stack", aka the cache)
@__mem_stack_ptr___:
  pb    @__mem_stack__
@__mem_stack__:
  alloc MEM_STACK_SPACE__

; heap starts here
@__heap__:
  alloc HEAP_SPACE__
    