; tma-16 assembly code
; Code generated by the MPL compiler

; entry point of the program
jmp @__start__
    
; unimplemented feature: (<built-in function readln>)

; function foo()
@foo:

; unimplemented feature: (return (+ x 1)) 
  pop ip

; entry point of the program
@__start__:

; unimplemented feature: (setq i 68) (format t "~a" (+ (foo i) "\n")) (format t "~a" "Nice\n") 
  halt ; end of program
